### ISSUE TITLE
psychicDamage가 작동하지 않습니다

### ISSUE THREAD

**Issue by Hinoto04** [noonmaru/heroes#100]
![image](https://user-images.githubusercontent.com/61084127/101645189-6a12c180-3a79-11eb-8ff2-c6e3bd191682.png)
일단 psychicDamage가 활성화조차 되지 않은 모습입니다.

활로 화살 발사 시 해당 화살 이름을 PlusDamage로 바꾸고
만약 적중 시 맞은 엔티티에게 psychicDamage로 공격력에 비례해 피해를 주는 방식입니다.
![image](https://user-images.githubusercontent.com/61084127/101645413-b1994d80-3a79-11eb-88e0-f0d368cdb028.png)

데미지가 들어가지도 않을 뿐더러, 종종 화살이 맞지 않고 튕겨나오고,
맨 위 사진처럼 psychicDamage조차 활성화되어있지 않습니다.

어떻게 해결할 수 있을까요?

**Comment by realteusu** [comment]
`concept.damage`의 값을 받아올려면, `AbilityConcept`의 `init`에서 먼저 초기 `Damage`값을 먼저 설정해주셔야 합니다.

![Damage 설정](https://user-images.githubusercontent.com/71732701/101659454-b0c9d280-3a0b-11eb-9805-afa52ef2d4a9.png)

또한 데미지를 설정하는 방법도 여러가지가 있습니다.

자세한 `Damage` 관련 정보는 [위키 - Damage](https://github.com/noonmaru/psychics/wiki/Damage)에서 확인해주세요.

**Comment by Hinoto04** [comment]
이미 설정해놨습니다
RANGED에 1.0 으로 되어있습니다

**Comment by noonmaru** [comment]
EntityDamageByEntityEvent 는 피격을 받은 Entity를 대상으로 Listener를 호출합니다.

위 코드같은경우 능력 소유자가 맞을때 적용되겠네요

https://github.com/noonmaru/psychics/wiki/Event#provider

여길 참고해보세요

**Comment by Hinoto04** [comment]
![image](https://user-images.githubusercontent.com/61084127/101762692-1491ef80-3b21-11eb-97fb-29538b89588e.png)
아무래래도 활을 쏜 사람이 능력자다보니
shooter까지 가야 하네요.
이제 능력이 제대로 작동합니다.

하지만 이와 함께 새로운 문제가 등장했으니
자기 자신을 맞출 경우
![image](https://user-images.githubusercontent.com/61084127/101762831-41de9d80-3b21-11eb-89d0-b3df414e6e27.png)
이런 오류가 납니다

아무래도 자기 자신에게 psychicDamage 함수를 사용할 수 없나봅니다
어떻게 해결할 수 있을까요?

**Comment by Hinoto04** [comment]
자기 자신한텐 안쏘는걸로 하죠
