### ISSUE TITLE
와탈이마시타에 버그가 생겼습니다...

### ISSUE THREAD

**Issue by neck1203** [noonmaru/heroes#101]
와칼이마시타에 검이 소환되지 않습니다...

**Comment by paring-chan** [comment]
ProtocolLib 최신버전으로 업데이트 해보세요

**Comment by neck1203** [comment]
>이미 ProtocolLib은 최신버젼입니다

**Comment by ghost** [comment]
사용시 빨간색 글씨로 쓰인 긴 오류 (stacktrace) 같은건 콘솔에 안나오나요?
가능하시면 콘솔 로그 첨부 부탁드립니다.

**Comment by neck1203** [comment]
아 해결되었습니다
감사합니다

**Comment by ghost** [comment]
해켤되었으면 이슈 닫아주시면 감사하겠습니다. :)
