### ISSUE TITLE
직선수리검이 마나가 줄어들지 않습니다.

### ISSUE THREAD

**Issue by GGumin** [noonmaru/heroes#103]
직선수리검을 사용하는데 나머지 기존 능력들은 마나가 줄어드는데 직선수리검은 난사해도 줄어들지가 않고 가만히 있습니다..

**Comment by bucket1582** [comment]
원본 코드에는 cost가 30.0으로 되어있는 것으로 보아, 어떠한 설정도 바꾸지 않았을 때, 30이 떨어져야 하는 것으로 보입니다. 그런데 직선수리검을 난사해도 줄어들지 않는다면, Psychics 플러그인 하위 폴더에 있는 psychics 폴더의 .yml 파일에서 직선 수리검 능력에 관한 cost가 0으로 설정되어 있지는 않은지 확인 해보는 것이 좋을 듯합니다.
