### ISSUE TITLE
intelliJ를 시작할때

### ISSUE THREAD

**Issue by ganjangS** [noonmaru/heroes#122]
https://github.com/noonmaru/psychics-abilities를 적용하라고 했는데
계속 해서 
Could not find com.github.noonmaru:tap:3.2.4.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/noonmaru/tap/3.2.4/tap-3.2.4.pom
  - https://papermc.io/repo/repository/maven-public/com/github/noonmaru/tap/3.2.4/tap-3.2.4.pom
  - https://jitpack.io/com/github/noonmaru/tap/3.2.4/tap-3.2.4.pom
  - file:/C:/Users/c/.m2/repository/com/github/noonmaru/tap/3.2.4/tap-3.2.4.pom
Required by:
    project :abilities:sample

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
라고 빨간 글씨로 나오는건 어떻게 해야하나요

**Comment by jhjakekim** [comment]
이거 
abilities 폴더 아래 build.gradle.kts에서
subprojects 에 dependencies 부분에 있는
compileOnly("com.github.noonmaru:tap:3.2.4") 를
compileOnly("com.github.noonmaru:tap:3.2.5")로 고쳐주시면 됩니다

**Comment by myoun** [comment]
해결되셨으면 이슈를 닫아주세요.
