### ISSUE TITLE
제가 영어를 몰라서 적용방법, 사용방법 좀 알려주세요.

### ISSUE THREAD

**Issue by SPMKIRON** [noonmaru/heroes#81]
제가 영어를 몰라서 적용방법, 사용방법 좀 알려주세요.

**Comment by realteusu** [comment]
[위키](https://github.com/noonmaru/psychics/wiki)를 참고해주세요.

플러그인 적용은 `플러그인 설치`를 확인해주시면 되고,
초능력 사용방법은 `초능력 구성`을 확인해주시면 됩니다.

**Comment by SPMKIRON** [comment]
근데 0.9.3버전은 1.15.2버전 적용 되나요?

**Comment by realteusu** [comment]
1.13.2 ~ 1.16.4까지 지원됩니다.
[위키](https://github.com/noonmaru/psychics/wiki/Server)에도 버전은 나와있습니다.

**Comment by SPMKIRON** [comment]
위키를 보고 따라 했는데

[Kotlin] Enabling Kotlin v1.4.10
[Kotlin] Kotlin library loaded
[InvFX] Enabling InvFX v1.3.0

얘네는 나오는데

[Psychics] Enabling Psychics v0.6.0
[Psychics] Loaded abilities(0):
[Psychics] Loaded psychics(0):

얘네는 안 나오네요

**Comment by SPMKIRON** [comment]
그리고 능력(Psychics.jar)이 적용이 안되고

이런 메세지가 뜨네요.

[17:07:00 ERROR]: Could not load 'plugins\Psychics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
        at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-390]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-390]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-390]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by SPMKIRON** [comment]
또 제가 이런걸 몰라서 빌드하기랑 구성하기,작성하기,속성변경하기도 뭔지 모르겠고,능력 개발과 시스템은 어떻게,그리고 어디다 쓰는건가요?

**Comment by devil0414** [comment]
서버 버젼은 반드시 1.16.4이어야 합니다.
플러그인 적용 후 서버 한 번 돌리세요.
그러면 플러그인 폴더에 psychics라는 폴더가 생깁니다. 그안에 있는 abilities 폴더에 능력들을 집어넣습니다. 그리고 psychics 폴더 안에 psychics라는 폴더가 하나 더 있는데 거기안에 들어가서 <원하는 이름>.yml파일을 생상합니다. 그리고 그것을 메모장 또는 노트패드로 열어서 다음과 같이 작성합니다.
abilities:
  <원하는 이름>:
    ability: <abilities 폴더에 넣었던 파일이름(.jar은 생략)
이렇게 한다음에 서버를 돌리면 플러그인이 적용됩니다.

**Comment by realteusu** [comment]
> 서버 버젼은 반드시 1.16.4이어야 합니다.
> 플러그인 적용 후 서버 한 번 돌리세요.
> 그러면 플러그인 폴더에 psychics라는 폴더가 생깁니다. 그안에 있는 abilities 폴더에 능력들을 집어넣습니다. 그리고 psychics 폴더 안에 psychics라는 폴더가 하나 더 있는데 거기안에 들어가서 <원하는 이름>.yml파일을 생상합니다. 그리고 그것을 메모장 또는 노트패드로 열어서 다음과 같이 작성합니다.
> abilities:
> <원하는 이름>:
> ability: <abilities 폴더에 넣었던 파일이름(.jar은 생략)
> 이렇게 한다음에 서버를 돌리면 플러그인이 적용됩니다.

버전은 항상 1.16.4가 아니어도 됩니다. 위키에도 등재되어 있듯이 [1.13.2 ~ 1.16.4까지 지원](https://github.com/noonmaru/psychics/wiki/Server)이 되는데 `api-version`이 1.16으로 설정이 돼 오류가 났던 것입니다. 이것은 버그이므로 일단 풀리퀘를 걸었습니다(#86). 나머지는 이분을 참고하시거나 [위키](https://github.com/noonmaru/psychics/wiki)도 참고해주시면 감사하겠습니다.

**Comment by SPMKIRON** [comment]
근데 제가 paper mc에서 1.16.4를 찾기 어려워서 그런데 혹시 링크 있나요?
답 안해주셔도  됩니다.

**Comment by realteusu** [comment]
[Paper 1.16.4 Latest Build](https://papermc.io/api/v1/paper/1.16.4/latest/download)입니다.

 - [PaperMC](https://papermc.io/)에서 [Downloads](https://papermc.io/Downloads) 누르시고 Build 아래 있는 버튼 클릭해 주시면 최신 버전 다운로드하실 수 있습니다.

**Comment by cog25** [comment]
@SPMKIRON Fixed

**Comment by SPMKIRON** [comment]
덕분에  플러그인 설치는 끝냈습니다. 작성하기에 yaml,Gradle Multiproject가 뭐고 빌드하기,시스템,능력개발은 어디다 쓰죠?
그리고 정말 감사합니다.이렇게 친절하신분들 처음 보내요.

**Comment by realteusu** [comment]
`yaml`은 `.yml`이란 파일 확장명을 가진 언어입니다. `yaml`은 대부분 파일로 설정이나 정보를 보관하는데 사용됩니다. `psychics`도 `yaml`을 통해 여러 가지 능력에 관해서 설정할 수 있습니다.

 - 참고 : [What is YAML?](https://blog.stackpath.com/yaml/#:~:text=Definition,used%20to%20write%20configuration%20files.)

`Gradle Multi-project`는 `root` 프로젝트가 있고 다른 여러가지 `subproject`들이 구성돼있는 걸 `Gradle Multi-project`라고 합니다. 예시로 [psychics-abilities](https://github.com/noonmaru/psychics-abilities)라는 `root` 프로젝트가 있으면 `abilities` 안에 있는 능력들이 `subproject`라고 할 수 있겠네요.

- 참고 - [Multi-Project Builds in Gradle](https://docs.gradle.org/current/userguide/multi_project_builds.html)

위키에서 [빌드하기](https://github.com/noonmaru/psychics/wiki/%EB%B9%8C%EB%93%9C%ED%95%98%EA%B8%B0)는:
`psychics`을 수정할때만 확인하시면 됩니다. 수정을 안해도 된다면 [빌드하기](https://github.com/noonmaru/psychics/wiki/%EB%B9%8C%EB%93%9C%ED%95%98%EA%B8%B0)는 무시하셔도 됩니다.

소프트웨어에서 빌드하기는:
사람이 읽을 수 있는 코드를 기계의 언어로 변환(다른 용어로 컴파일) 하는 과정을 빌드라고 합니다.

 - 참고 - [Software build](https://en.wikipedia.org/wiki/Software_build), [What is software build- All you need to know!](https://medium.com/webgentle/what-is-the-software-build-all-you-need-to-know-4046b0e674bb)

[위키](https://github.com/noonmaru/psychics/wiki)에서의 시스템은 아마도 이 플러그인이 어떻게 작동되는지 설명하는 섹션 같습니다. 이 플러그인의 기능을 알고 싶으면 여기를 참고하시면 될 것 같습니다.

[위키](https://github.com/noonmaru/psychics/wiki)에서의 능력 개발은 새로운 능력을 작성할 수 있는 방법을 설명하는 섹션 같습니다. 새로운 능력을 작성하지 않고, 기존에 있는 능력을 사용하신다면 이 섹션은 스킵 하셔도 무방합니다.

저도 틀릴 수도 있고, 잘못된 정보가 있을 수도 있으니 잘못된 부분이 있으면 알려주시면 감사하겠습니다!

**Comment by SPMKIRON** [comment]
혹시  yaml은 프로그램 인가요?네이버에 쳐보긴 했지만 사이트가 이상해서 다운로드 방법이나 설치링크를 보내주시면 안될까요?
참고로 버전은 1.16.4로 바꿨습니다.

**Comment by cog25** [comment]
@SPMKIRON yaml은 파일 형식입니다.

메모장이나, VS Code 등 텍스트 에디터로 여셔서 수정하면 됩니다 :D

**Comment by SPMKIRON** [comment]
상관없지만 혹시 .class는 어떻게 쓰는건가요?

**Comment by cog25** [comment]
@SPMKIRON 죄송하지만,어디에 `.class`가 나오는지 설명 부탁드립니다.

**Comment by SPMKIRON** [comment]
그냥 제가 모드 작업을 하는데 있어서 물어 보았습니다.
실례되셨다면 죄송합니다.

**Comment by paring-chan** [comment]
> 상관없지만 혹시 .class는 어떻게 쓰는건가요?

클래스 파일은 jvm 언어 코드가 컴파일 된 바이트코드 파일입니다. 여기선 건드릴 일 없을건데..

**Comment by SPMKIRON** [comment]
아 그냥 궁금해서 물어본겁니다.죄송합니다.

**Comment by cog25** [comment]
@SPMKIRON @noonmaru Please Close Issue.
