### ISSUE TITLE
진짜 소소하지만 올려봅니다.

### ISSUE THREAD

**Issue by JustSolUser** [noonmaru/heroes#83]
플레이어의 레벨에 따라 특정 값이 늘어나게 하는 코드를 만들려고 하는데 이 레벨을 나타내는 코드를 모르겠습니다..

**Comment by realteusu** [comment]
데미지는 자동으로 레벨, 방어력에 따라 [자동으로 계산](https://github.com/noonmaru/psychics/wiki/%EB%8A%A5%EB%A0%A5%EC%B9%98%EC%99%80-%EC%8A%A4%ED%83%AF%EA%B3%84%EC%88%98)이 됩니다.
초기 설정(Initialize)나 yaml 수정을 통해 기본 데미지랑 데미지 타입을 설정할 수 있습니다.
자세한 설명은 [위키](https://github.com/noonmaru/psychics/wiki)에도 있으니 [위키](https://github.com/noonmaru/psychics/wiki)도 참고해주시면 감사하겠습니다.

**Comment by JustSolUser** [comment]
흠.. 일단 알겠습니다
나중에 어떻게든 해보겠습니다
감사합니다!
