### ISSUE TITLE
Travis CI 이동

### ISSUE THREAD

**Issue by realteusu** [noonmaru/heroes#87]
과거에 Travis CI는 travis-ci.com (Private)과 travis-ci.org (Public)를 사용하여 Private / Public repository를 구분했지만 2018년 5월 이후 신규 사용자가 travis-ci.com에서 Private / Public repository를 사용할 수 있게 됨에 따라 올해 12월 31일 travis-ci.org가 폐쇄된다고 합니다. 그래서 travis-ci.com으로 migration 하시는 건 어떨지 의견을 내봅니다.

관련 문서 - [Migrating repositories to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

**Comment by noonmaru** [comment]
엑..
확인해보겠습니다.
