### ISSUE TITLE
IDEA psychics-abilities 적용 문제

### ISSUE THREAD

**Issue by 2006Ted** [noonmaru/heroes#89]
psychics-abilities/abilities/build.gradle.kts 파일에서 3.2.4를 3.2.5로 교체했는데 IntelliJ IDEA에 
적용시키는 방법을 모르겠습니다.

**Comment by realteusu** [comment]
[위키 - Hello Ability!](https://github.com/noonmaru/psychics/wiki/Hello-Ability%21)에서 `3.모듈 인식시키기`의 과정을 한번 더 반복하시면 됩니다. `build.gradle` 파일을 바꿨을때는 빌드를  다시 하시면 됩니다.
